# ============ DATASOURCE ============
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.connection-test-query=SELECT 1
spring.datasource.hikari.data-source-properties.sslmode=require

# ============ JPA / HIBERNATE ============
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ============ THYMELEAF ============
spring.thymeleaf.cache=false

# ============ SERVER ============
server.port=${PORT:8080}

spring.jpa.open-in-view=false
# ============ UPLOAD ============
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB

app.upload.dir=uploads